### ISSUE TITLE
Issues with starter

### ISSUE THREAD

**Issue by jonniebigodes** [georgewilde/gatsby-starter-wilde-creations#1]
Hi @georgewilde i checked out your starter and there's a couple of issues you need to address. I noticed that you're using Storybook in this starter. I tested it out and when me/another user tries to use this and goes about trying out Storybook. He/she will be presented with the [following error](https://gist.github.com/jonniebigodes/7c8e7b0a64c14c7686ff20e946c0f6e2). Upon checking the code you're using the old configuration with the new version of Storybook i.e >=5.3 and the way to setup Storybook changed quite a bit. You can read more about it handles configuration in [here](https://medium.com/storybookjs/storybook-5-3-83e114e8797c). Also if you can take a look at [this](https://github.com/gatsbyjs/gatsby/issues/20624#issuecomment-575284226) for a more detailed way to setup Storybook in Gatsby with the new version. 

Also if you don't mind add in a script to a normal development mode, so that the user will have options when he tries to setup a new website using the starter.

And finally the the link in the readme to the storybook used by this starter is pointing to the actual website.

Feel free to provide feedback

**Comment by georgewilde** [comment]
Thanks @jonniebigodes for taking the time to raise these issues. I'll take a look and get back to you shortly.

**Comment by georgewilde** [comment]
@jonniebigodes I've made some changes today and pushed them to master. Feel free to take a look, any thoughts or suggestions are very welcome. If there are any other changes you would suggest, I'll do them in a PR next time :)

**Comment by jonniebigodes** [comment]
@georgewilde i've taken a look and so far it's all good, it's working.

A couple of things i forgot to mention in the description:
- Adding `@storybook/addon-viewport` was a nice touch on your end, as in this day and age of testing and enforcing best practices. Really that was nice thing for you include out of the box. 
- I saw that you included `storybook-addon-jsx` which goes a long way in terms of allowing seeing what is being used in Storybook, but have you considered including `@storybook/addon-storysource`, i think that this addon will give a better picture to not only the developer but to a whole team of developers? 
- Also i saw that you included `@storybook/addon-knobs` aswell, but if you can include a sample on how to use it i think it will go a long way, 

As a side note, a more particular note, really nice job in putting this up together, it was a nice touch on your part. More specifically for the keypoints that are sometimes left out, i.e the testing aspect of development. 
I really hope this takes off and gets widespread and used as a boilerplate starter.

Feel free to provide feedback

**Comment by georgewilde** [comment]
Thank you @jonniebigodes, your comments mean a lot and I really appreciate your feedback. I will definitely check out @storybook/addon-storysource and add an example button component that I can demonstrate how to use the "knobs" and "actions" addons.

I agree that testing is often an afterthought but hopefully, by making that easier for people starting off we can change that :)

**Comment by georgewilde** [comment]
Hi @jonniebigodes I just thought I'd let you know I've added a button component with an example of how to use the knobs addon. I've also made quite a few other improvements. I'd love to get any thoughts you may have on this update as your feedback so far has been really helpful. Many thanks :)

**Comment by jonniebigodes** [comment]
@georgewilde i checked the starter and it seems that the starter is breaking once more with storybook.

Running `yarn storybook` throws [this](https://gist.github.com/jonniebigodes/816d0d7b13b9d3d47836a4c5ccd05fb7) error. At first glance I think that it might be related to the gatsby preset you added in your latest commit. 

Also if you're willing to help spread a vscode plugin for storybook i think that the community would appreciate it and the people behind it aswell, [here is their GitHub repo](https://github.com/storybookjs/vs-code-plugin) check it out and let me know

**Comment by georgewilde** [comment]
Aw I'm so sorry @jonniebigodes I wasn't seeing that error as it only occurs when there hasn't been a Gatsby build for the project and I had always done one before running Storybook. I've just pushed an update and this should now be fixed.

I have had a look at that Aespo plugin and it looks great. I actually use Webstorm but I've given the project a star and will mention it to all my colleagues who use VS Code and tell them they should give it a try.

Feel free to try and run this repo again and let me know if you experience any further issues. Thanks again for all your feedback mate :)

**Comment by jonniebigodes** [comment]
@georgewilde when you can just as a safe guard update the jest.config.js`, more specifically the key `testPathIgnorePatterns` to include the static folder generated by Storybook. 
Turning it into:
```javascript
testPathIgnorePatterns: [`node_modules`, `\\.cache`, `<rootDir>.*/public`, `<rootDir>/storybook-static/`],
```

I know that your setup has the output of the build to be on a different folder, but another person migh update it and set the default and it could introduce unecessary errors.

Asides from that. It seems to be working nicely. And thanks for the star, i think the people will like it alot that their work is being spread out.

**Comment by georgewilde** [comment]
Good suggestion there @jonniebigodes I've added that into the Jest config now.
Feel free to mention this starter to anyone who you think might find it useful, it would be great to see it being used :)

Thanks again for all your suggestions and time, it's much appreciated.

**Comment by jonniebigodes** [comment]
@georgewilde no problem whatsoever...i've just mentioned the starter in a tweet to help spread the starter

**Comment by georgewilde** [comment]
@jonniebigodes that is awesome mate, I really appreciate it. Thank you 👍
